# site properties and page defaults
title: LIN Lab 
subtitle: Where light interacts with nanomaterials
description: An engaging 1-3 sentence 
header: images/cell1-01.jpg
footer: images/SJTU.jpg

# site social media and other links
links:
  email: linli92@sjtu.edu.cn
  orcid: 0000-0001-8713-9213
  google-scholar: https://scholar.google.com.hk/citations?user=Zc3cFgwAAAAJ&hl=zh-CN
  website: https://bme.sjtu.edu.cn/Web/FacultyDetail/917
  
### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
