- id: doi:10.1007/s44258-023-00010-2
  type: paper
  description: We report the use of surface-enhanced Raman scattering nanotags embedded in ex-vivo animal tissues for direct and quantitative measurements of light attenuation and spectroscopic detection depth at both the NIR-I and NIR-II spectral windows.
  date: '2023-08-14'
  authors: Li Lin*, Haoqi He, Ruiyang Xue, Yumin Zhang, Ziwen Wang, Shuming Nie*, Jian Ye*
  image: images/Papers/MEDX2023.jpg
  tags:
    - SERS
    - Detection depth assessment
    - Second near-infrared window
    - NIR-II

- id: doi:10.1002/advs.202301721
  image: images/Papers/AS2023.jpg
  authors: Zongyu Wu, Binge Deng*, Yutong Zhou, Haoqiang Xie, Yumin Zhang, Li Lin*, Jian Ye*
  tags: 
    - Transmission Raman spectroscopy
    - noninvasive in vivo detection
      
- id: doi:10.1002/viw.20230022
  image: images/Papers/View.jpg
  authors: Yumin Zhang, Li Lin*, Jian Ye*
  tags: 
    - Transmission Raman spectroscopy
    - Depth estimation

- id: doi:10.1016/j.saa.2022.122163
  image: images/Papers/SAPA-2023.jpg
  authors: Wenfang Wang, Bowen Shi, Chang He, Siyi Wu, Lan Zhu, Jiang Jiang, Lingyun Wang, Li Lin*, Jian Ye*, Huan Zhang*
  tags:
    - Euclidean distance
    - Raman spectroscopy
    - EDRS
    - Stomach cancer prognosis

- id: doi:10.1002/smtd.202201334 
  image: images/Papers/Smallmethods-2023.jpg
  authors:
   - Zongyu Wu
   - Binge Deng*
   - Yutong Zhou
   - Haoqiang Xie
   - Yumin Zhang
   - Li Lin*
   - Jian Ye*
  tags: 
    - transmission Raman spectroscopy
    - Ultrahigh detection depth in biological tissues

- id: doi:10.1021/acs.jpcc.2c02512
  image: images/Papers/JPCC-2022.jpg
  authors: Haoqi He, Shuo Zhu, Yumin Zhang, Jian Ye*, Li Lin*
  tags:
    - Second near-infrared window
    - NIR-II
    - SERS tag
    - Au nanorod

- id: doi:10.3390/photonics9060429
  authors: Zongyu Wu, Ziwen Wang, Haoqiang Xie, Yiming Wang, Haoqi He, Shuming Nie, Jian Ye, Li Lin*
  image: images/Papers/Photonics-2022.jpg
  tags:
    - Bronchoscopy
    - Lung Tissue
    - SERS Nanoparticle
    - GERTs
   
- id: doi:10.1021/acsami.2c01063
  authors: Shuo Zhu, Binge Deng, Fugang Liu, Jin Li, Li Lin, Jian Ye*
  tags:
    - Au nanorod
     
- id: doi:10.1016/j.mtbio.2022.100205
  authors: Yao Lu, Li Lin*, Jian Ye*
  image: images/Papers/mtb-2022.jpg
  tags:
    - SERS
    - Metabolite detection

- id: doi:10.1063/5.0047578 
  authors: Li Lin, Xinyuan Bi, Yuqing Gu, Fu Wang, Jian Ye*
  image: images/Papers/JAP-2021.jpg
  tags:
    - review
    - SERS

- id: doi:10.1142/S1793545821410017
  authors: Yumin Zhang#, Li Lin#, Jing He, Jian Ye*
  image: images/Papers/JIOHS-2021.jpg
  tags:
    - Au nanorod
    - SERS
    - detection depth assessment
   
    
- id: doi:10.1021/acs.jpcc.0c09552
  authors: Li Lin, Weiming Ji, Lu-Wen Zhang*, Jian Ye*
  image: images/Papers/JPCC-2021.JPG
  tags:
    - Molecular dynamics
    - GERTs
    - Plasmonic junction

- id: doi:10.1021/acsnano.7b08224
  image: images/Papers/ACSNano-2018.png
  tags:
    - SERS
    - GERTs
    - Plasmonic junction

- id: doi:10.1021/acs.nanolett.5b02931
  image: images/Papers/nanolett-2015.jpg
  tags:
    - SERS
    - GERTs
    - Plasmonic junction

- id: doi:10.1039/c5cc06599b
  image: images/Papers/CC-2015.jpg
  tags:
    - SERS
    - GERTs
    - Plasmonic junction



    


   
