 
- id: doi:10.1007/s44258-023-00010-2
  type: paper
  description: We report the use of surface-enhanced Raman scattering nanotags embedded in ex-vivo animal tissues for direct and quantitative measurements of light attenuation and spectroscopic detection depth at both the NIR-I and NIR-II spectral windows.
  date: '2023-08-14'
  authors:
  - Li Lin*
  - Haoqi He
  - Ruiyang Xue
  - Yumin Zhang
  - Ziwen Wang
  - Shuming Nie*
  - Jian Ye*
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs44258-023-00010-2/MediaObjects/44258_2023_10_Figa_HTML.png?as=webp
  tags:
    - SERS
    - Detection depth assessment
    - Second near-infrared window
    - NIR-II

- id: doi:10.1002/advs.202301721
  image: https://onlinelibrary.wiley.com/cms/asset/f03586ad-3259-4e29-9a08-d40c39e5449c/advs5948-fig-0001-m.jpg
  authors: Zongyu Wu, Binge Deng*, Yutong Zhou, Haoqiang Xie, Yumin Zhang, Li Lin*, Jian Ye*
  tags: 
    - transmission Raman spectroscopy
    - noninvasive in vivo detection
      
- id: doi:10.1002/viw.20230022
  images: images/papers/View.jpg
  authors: Yumin Zhang, Li Lin*, Jian Ye*
  tags: 
    - transmission Raman spectroscopy
    - Depth estimation
    
- id: doi:10.1016/j.saa.2022.122163
  images: images/papers/SAPA-2023.jpg
  authors: Wenfang Wang, Bowen Shi, Chang He, Siyi Wu, Lan Zhu, Jiang Jiang, Lingyun Wang, Li Lin*, Jian Ye*, Huan Zhang*
  tags:
    - Euclidean distance
    - Raman spectroscopy
    - EDRS
    - Stomach cancer prognosis

- id: doi:10.1002/smtd.202201334 
  images: images/papers/Smallmethods-2023.jpg
  authors:
   - Zongyu Wu
   - Binge Deng*
   - Yutong Zhou
   - Haoqiang Xie
   - Yumin Zhang
   - Li Lin*
   - Jian Ye*
  tags: 
    - transmission Raman spectroscopy
    - Ultrahigh detection depth in biological tissues

- id: doi:10.1021/acs.jpcc.2c02512
  images: images/papers/JPCC-2022.jpg
  authors:
   - Haoqi He
   - Shuo Zhu
   - Yumin Zhang
   - Jian Ye*
   - Li Lin*
  tags:
   - Second near-infrared window
   - NIR-II
   - SERS tag
   - Au nanorod
  
  
    
